services:
  - type: background
    name: task-cron-job-render
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api/schedule-meeting.py"
    envVars:
      - key: ZOOM_CLIENT_ID
        fromSecret: ZOOM_CLIENT_ID
      - key: ZOOM_CLIENT_SECRET
        fromSecret: ZOOM_CLIENT_SECRET






