services:
  - type: background worker
    name: zoom-scheduler
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api/schedule-meeting.py"
    envVars:
      - key: CLIENT_ID
        fromEnv: CLIENT_ID
      - key: CLIENT_SECRET
        fromEnv: CLIENT_SECRET




