services:
  - type: cron
    name: zoom-scheduler
    env: python3
    schedule: "0 * * * *" # This runs the job every hour
    command: "api/schedule-meeting.py"
    envVars:
      - key: CLIENT_ID
        value: your_zoom_client_id
      - key: CLIENT_SECRET
        value: your_zoom_client_secret
      - key: REDIRECT_URI
        value: your_redirect_uri



