# render.yaml

services:
  - name: cron
    env:
      - key: CLIENT_ID
        value: YOUR_ZOOM_CLIENT_ID_HERE
      - key: CLIENT_SECRET
        value: YOUR_ZOOM_CLIENT_SECRET_HERE
    build_command: python -m pip install -r requirements.txt
    start_command: python api/schedule-meeting.py





