services:
  - name: task-cron-job-render
    type: background
    env:
      - key: CLIENT_ID
        scope: private
      - key: CLIENT_SECRET
        scope: private
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python api/schedule-meeting.py

